name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./api --build-arg app_env=production; docker build ./frontend --build-arg app_env=production; docker build ./db
    
    - uses: actions/checkout@v3
    - name: Start the Docker
      run: docker-compose up
